version: 2
jobs:
  build:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt"  }}
    - run:
        command: |
          if true; then
            make install
          else
            make install
          fi
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        command: . venv/bin/activate
        make lint
        name: run lint
workflows:
  main:
    jobs:
    - build-and-test
  version: 2